services:
  oracle_deploy:
    build:
      context: ..
      dockerfile: container_database_deployment/Dockerfile
    image: pifsc/${PROJECT_CONTAINER_NAME}:latest
    container_name: ${PROJECT_CONTAINER_NAME}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
