services:
  oracle_deploy:
    build:
      context: ..
      dockerfile: container_database_deployment/Dockerfile
    image: pifsc/${COMPOSE_PROJECT_NAME}:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}_default